// Written by tools/commands.py generate. Do not edit: change the lists in that file and run it again.
// Built from pdfTeX 3.141592653-2.6-1.40.29 (TeX Live 2026/Arch Linux).
// 399 symbols, 107 composite symbols, 227 structural commands and 27 primitives.

const words = (...rows: string[]) => new Set(rows.join('').trim().split(' '))

/** The commands that a formula may use, without their backslash. */
export const COMMANDS: ReadonlySet<string> = words(
  'Aboxed AmS And Approxcolon Arrowvert Bbbk Big Bigg Biggl Biggm Biggr Bigl Bigm Bigr Box Bumpeq Cap ',
  'Colonapprox Colondash Coloneq Coloneqq Colonsim Cup Dashcolon Delta Diamond Doteq Downarrow Eqcolon ',
  'Eqqcolon Finv Game Gamma Im Join Lambda Leftarrow Leftrightarrow Lleftarrow Longleftarrow ',
  'Longleftrightarrow Longrightarrow Lsh Omega Phi Pi Pr Psi Re Relbar Rightarrow Rrightarrow Rsh Sigma ',
  'Simcolon Subset Supset Theta Uparrow Updownarrow Upsilon Vdash Vert Vvdash Xi acute adjustlimits aleph ',
  'allowbreak alpha amalg angle approx approxcolon approxeq arccos arcsin arctan arg arraystretch arrowvert ',
  'ast asymp atop backepsilon backprime backsim backsimeq backslash bar barwedge because begin beta beth ',
  'between big bigcap bigcirc bigcup bigg biggl biggm biggr bigl bigm bigodot bigoplus bigotimes bigr ',
  'bigsqcup bigstar bigtimes bigtriangledown bigtriangleup biguplus bigvee bigwedge binom blacklozenge ',
  'blacksquare blacktriangle blacktriangledown blacktriangleleft blacktriangleright bm bmod boldsymbol bot ',
  'bowtie boxdot boxed boxminus boxplus boxtimes brace braceld bracelu bracerd braceru bracevert brack ',
  'breve bullet bumpeq cap cdot cdotp cdots centerdot cfrac check checkmark chi choose circ circeq ',
  'circlearrowleft circlearrowright circledR circledS circledast circledcirc circleddash clap cline ',
  'clubsuit colon colonapprox colondash coloneq coloneqq colonsim complement cong coprod cos cosh cot coth ',
  'cramped csc cup curlyeqprec curlyeqsucc curlyvee curlywedge curvearrowleft curvearrowright dagger daleth ',
  'dasharrow dashcolon dashleftarrow dashrightarrow dashv dbinom dblcolon ddagger ddddot dddot ddot ddots ',
  'defaultscriptratio defaultscriptscriptratio deg delta det dfrac diagdown diagup diamond diamondsuit ',
  'digamma dim displaybreak displaylimits displaystyle div divideontimes dot doteq doteqdot dotplus dots ',
  'dotsb dotsc dotsi dotsm dotso doublebarwedge doublecap doublecup downarrow downdownarrows ',
  'downharpoonleft downharpoonright ell emph emptyset end enskip enspace ensuremath epsilon eqcirc eqcolon ',
  'eqqcolon eqref eqsim eqslantgtr eqslantless equiv eta eth exists exp fallingdotseq fbox flat forall frac ',
  'frown gamma gcd ge genfrac geq geqq geqslant gets gg ggg gggtr gimel gnapprox gneq gneqq gnsim grave ',
  'gtrapprox gtrdot gtreqless gtreqqless gtrless gtrsim gvertneqq hat hbar hbox hdots hdotsfor heartsuit ',
  'hfil hfill hline hom hookleftarrow hookrightarrow hphantom hskip hslash hspace idotsint iff iiiint iiint ',
  'iint imath impliedby implies in inf infty injlim int intercal intertext intop iota jmath joinrel kappa ',
  'ker kern l lVert label lambda land langle lbrace lceil ldotp ldots le leadsto left leftarrow ',
  'leftarrowtail leftharpoondown leftharpoonup leftleftarrows leftrightarrow leftrightarrows ',
  'leftrightharpoons leftrightsquigarrow leftthreetimes leq leqq leqslant lessapprox lessdot lesseqgtr ',
  'lesseqqgtr lessgtr lesssim lfloor lg lgroup lhd lhook lim liminf limits limsup ll llap llcorner lll ',
  'llless lmoustache ln lnapprox lneq lneqq lnot lnsim log longleftarrow longleftrightarrow longmapsto ',
  'longrightarrow looparrowleft looparrowright lor lozenge lparen lq lrcorner ltimes lvert lvertneqq ',
  'maltese mapsto mapstochar mathbb mathbf mathbin mathcal mathchoice mathclap mathclose mathdollar ',
  'mathellipsis mathfrak mathinner mathit mathllap mathnormal mathop mathopen mathord mathparagraph ',
  'mathpunct mathrel mathring mathrlap mathrm mathsection mathsf mathsterling mathstrut mathtt ',
  'mathunderscore max mbox measuredangle medspace mho mid middle min minalignsep mkern mod models mp mskip ',
  'mspace mu multicolumn multimap nLeftarrow nLeftrightarrow nRightarrow nVDash nVdash nabla natural ncong ',
  'ndownarrow ne nearrow neg negmedspace negthickspace negthinspace neq nexists ngeq ngeqq ngeqslant ngtr ',
  'ni nleftarrow nleftrightarrow nleq nleqq nleqslant nless nmid nolimits nonumber not notag notin ',
  'nparallel nprec npreceq nrightarrow nshortmid nshortparallel nsim nsubseteq nsubseteqq nsucc nsucceq ',
  'nsupseteq nsupseteqq ntriangleleft ntrianglelefteq ntriangleright ntrianglerighteq nu nuparrow nvDash ',
  'nvdash nwarrow odot oint ointop omega ominus operatorname operatornamewithlimits oplus ordinarycolon ',
  'oslash otimes over overbrace overbracket overleftarrow overleftrightarrow overline overrightarrow ',
  'overset overunderset owns parallel partial perp phantom phi pi pitchfork pm pmb pmod pod prec precapprox ',
  'preccurlyeq preceq precnapprox precneqq precnsim precsim prescript prime prod projlim propto psi qquad ',
  'quad rVert rangle rbrace rbrack rceil ref relax relbar restriction rfloor rgroup rhd rho rhook right ',
  'rightarrow rightarrowtail rightharpoondown rightharpoonup rightleftarrows rightleftharpoons ',
  'rightrightarrows rightsquigarrow rightthreetimes risingdotseq rlap rmoustache rparen rq rtimes rvert ',
  'scriptscriptstyle scriptstyle searrow sec setminus sharp shortintertext shortmid shortparallel shoveleft ',
  'shoveright sideset sigma sim simcolon simeq sin sinh smallfrown smallint smallsetminus smallsmile smash ',
  'smashoperator smile spadesuit sphericalangle sqcap sqcup sqrt sqsubset sqsubseteq sqsupset sqsupseteq ',
  'square stackrel star strut subset subseteq subseteqq subsetneq subsetneqq substack succ succapprox ',
  'succcurlyeq succeq succnapprox succneqq succnsim succsim sum sup supset supseteq supseteqq supsetneq ',
  'supsetneqq surd swarrow tag tan tanh tau tbinom text textbf textellipsis textit textnormal textrm textsf ',
  'textstyle texttt textup tfrac theequation thepage theparentequation therefore theta thickapprox thicksim ',
  'thickspace thinspace tilde times to top triangle triangledown triangleleft trianglelefteq triangleq ',
  'triangleright trianglerighteq twoheadleftarrow twoheadrightarrow ulcorner underbrace underbracket ',
  'underleftarrow underleftrightarrow underline underrightarrow underset unlhd unrhd uparrow updownarrow ',
  'upharpoonleft upharpoonright uplus upsilon upuparrows urcorner vDash varDelta varGamma varLambda ',
  'varOmega varPhi varPi varPsi varSigma varTheta varUpsilon varXi varbigtriangledown varbigtriangleup ',
  'varepsilon varinjlim varkappa varliminf varlimsup varnothing varphi varpi varprojlim varpropto varrho ',
  'varsigma varsubsetneq varsubsetneqq varsupsetneq varsupsetneqq vartheta vartriangle vartriangleleft ',
  'vartriangleright vcentcolon vdash vdots vec vee veebar vert vphantom wedge widehat widetilde wp wr ',
  'xLeftarrow xLeftrightarrow xRightarrow xhookleftarrow xhookrightarrow xi xleftarrow xleftharpoondown ',
  'xleftharpoonup xleftrightarrow xleftrightharpoons xmapsto xrightarrow xrightharpoondown xrightharpoonup ',
  'xrightleftharpoons yen zeta ',
)

/** The environments that a formula may use. */
export const ENVIRONMENTS: ReadonlySet<string> = words(
  'equation equation* align align* gather gather* multline multline* alignat alignat* flalign flalign* ',
  'eqnarray eqnarray* split aligned gathered alignedat multlined lgathered rgathered cases cases* dcases ',
  'dcases* rcases rcases* drcases drcases* matrix pmatrix bmatrix Bmatrix vmatrix Vmatrix matrix* pmatrix* ',
  'bmatrix* Bmatrix* vmatrix* Vmatrix* smallmatrix psmallmatrix bsmallmatrix Bsmallmatrix vsmallmatrix ',
  'Vsmallmatrix smallmatrix* psmallmatrix* bsmallmatrix* Bsmallmatrix* vsmallmatrix* Vsmallmatrix* array ',
  'subarray spreadlines subequations ',
)
